apiVersion: v1
kind: Service
metadata:
  name: python-api-probe-service
  labels:
    app: python-api-probe
spec:
  selector:
    app: python-api-probe
  ports:
    - protocol: TCP
      port: 8080         # External service port
      targetPort: 5000 # Container's port
  type: NodePort
